default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "api" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "api_development" } %>

test:
  <<: *default
  database: api_test

production:
  <<: *default
  url: <%= ENV["API_DATABASE_PASSWORD"] %>
